<?php

namespace App\Models;

class Constants
{

    public static $sociedades = [
        'Sociedad en nombre colectivo',
        'Sociedad en comandita simple',
        'Sociedad en responsabilidad limitada',
        'Sociedad anónima',
        'Sociedad en comandita por acciones',
        'Sociedad cooperativa',
        'Sociedad por acciones simplificada'
    ];
    
    public static $tipos_formularios_salta = [
        'Tipo 1',
        'Tipo 2',
        'Tipo 3'
    ];

    public static $departamentos = [
        'Capital',
        'Rawson',
        'Chimbas',
        'Rivadavia',
        'San Lucía',
        'Pocito',
        'Caucete',
        'Jáchal',
        'Albardón',
        'Sarmiento',
        '25 de Mayo',
        'San Martín',
        'Calingasta',
        '9 de Julio',
        'Angaco',
        'Valle Fértil',
        'Iglesia',
        'Ullum',
        'Zonda'
    ];


    public static $cargos = [
        'CTO',
        'CTE',
        'CTF',
        'CTI',
        'Gerente',
        'Dueño',
        'Inversor',
        'Representante',
        'Abogado',
        'Empleado',
        'Apoderado',
        'Otro'
    ];
    public static $estados = [
        'aprobado',
        'reprobado',
        'en proceso',
        'con observaciones'
    ];

    public static $nombres_minas = [
        'Aguilar', 
        'Ajedrez ',
        'Cerro Moro ',
        'Cerro Negro',
        'Cerro Vanguardia ',
        'Don Nicolás',
        'Farallón Negro ',
        'Fénix ',
        'Gualcamayo ',
        'Manantial Espejo',
        'Mina Martha ',
        'Olaroz ',
        'Puna Operation ',
        'Río Turbio  ',
        'San José ',
        'Veladero',
        'Andacollo',
        'Cauchari-Olaroz ',
        'Americas Corp | JEMSE',
        'Córdoba ',
        'Lindero ',
        'Centenario-Ratones ',
        'El Pachón ',
        'Lama ',
        'Pastos Grandes ',
        'Potasio Río ',
        'Providencia ',
        'Sal de Vida ',
        'Salar del Rincón ',
        'Suyai',
        'Agua Rica ',
        'Goldcorp',
        'Cauchari ',
        'Filo del Sol',
        'Josemaría',
        'San Jorge ',
        'Tres Quebradas ',
        'Kachi ',
        'Amarillo Grande ',
        'Diablillos ',
        'El Quevar ',
        'Laguna Salada ',
        'Los Azules',
        'Mariana ',
        'Lithium ',
        'Navidad ',
        'PPG',
        'Sal de Los Ángele',
        'Salar del Hombre',
        'Muerto Norte',
        'Salar del Rincón-Argosy ',
        'Taca Taca ',
        'Taguas Oro ',
        'Altar',
        'Calcatreu ',
        'Cerro Blanco ',
        'Cerro Solo ',
        'Claudia ',
        'Del Carmen ',
        'Don Otto ',
        'Don Sixto ',
        'Gallego ',
        'Jagüelito ',
        'La Josefina ',
        'La Manchuria ',
        'Laguna Colorada ',
        'Las Calandrias ',
        'Lejano Plata ',
        'Meseta Central ',
        'Pingüino Oro ',
        'Potasio ',
        'Pular ',
        'Rincón ',
        'Río Grande ',
        'Río Grande ',
        'Sal de Oro ',
        'San Roque ',
        'Valle de Chita',
        'Virginia',
        'A Grade Trading',
        'Admiralty Resources',
        'Agnico-Eagle Mines ',
        'Allana Resources Inc',
        'Alphamin Resources Corp',
        'Andean Resources Ltd',
        'Andes Minerals SA',
        'Anglo American plc',
        'Anglogold Ashanti',
        'Antares Minerals Inc',
        'Antofagasta Minerals',
        'Aquiline Resources Inc',
        'AREVA Resources Canada Inc',
        'Argentex Mining Corporation',
        'Argentina Minera SA',
        'Argentina Power Mining Corp',
        'Argentine Frontier Resources Inc',
        'Artha Resources Corp',
        'AuEx Ventures Inc',
        'Austral Gold Ltd',
        'Ballad Gold & Silver Ltd',
        'Benetton',
        'Benton Resources Corp',
        'BHP Billiton Limited',
        'Blue Sky Uranium Corp',
        'BuenaventuraPeru',
        'Cadillac Ventures Inc',
        'Calypso Uranium Corp',
        'Canadian Gold Hunter Corp',
        'Cardero Resources Corp',
        'Cascadero Copper Corp',
        'Castillian Resources Corp',
        'Cauldron Energy Ltd',
        'Cementos Bio Bio SA',
        'CHC Venture Capital SA',
        'Coeur D’Alene Mines Corp',
        'Committee Bay Resources Ltd',
        'Cormine SEP',
        'Coro Mining Corp',
        'Davcha Resources Pty',
        'Delta Mutual Inc',
        'Denison Mines Corp',
        'Dixon, Perot & Champion Inc',
        'Electrum Mining Limited',
        'Elementos Limited',
        'Emprendimientos Mineros SA',
        'Entropy Resources Pty Ltd',
        'Exeter Resource Corporation',
        'Ferro',
        'FMC Lithium',
        'Fomicruz SE',
        'G4G Resources Ltd',
        'Geoandina Mining Corp',
        'Geocom Resources Corp',
        'Glencore Internacional AG',
        'Gold Fields LtdSudafrica',
        'Goldcorp Toronto Inc',
        'Golden Arrow Resources Corp',
        'Golden Minerals Company',
        'Golden Peaks Resources Ltd',
        'Guanaco Mining Company',
        'Hidefield Gold',
        'Hochschild',
        'Hunt Mountain Resources',
        'IAM Gold Corporation',
        'IMA Exploration Inc',
        'International Mineral Resources Ltd',
        'IPEEM',
        'Jinshan Minera Argentina SA',
        'JOGMEC',
        'Kinross Gold Corporation',
        'La Mancha Resources Inc',
        'Lake Resources NL',
        'Laramide Resources Ltd',
        'Latin American Minerals Inc',
        'Lithium Americas Corp',
        'Lithium One',
        'Lucadata SRL',
        'Lumina Copper Corp',
        'Magma Energy Corp',
        'Malbex Resources Inc',
        'Mansfield Minerals Inc',
        'Mariana Resources',
        'Marifil Mines Ltd',
        'MCC',
        'Mega Uranium Ltd',
        'Metallum',
        'Metropolitan Mining Inc',
        'Minamerica SA',
        'Minera AGAUCU SA',
        'Minera Andes Inc',
        'Minera Austral SA',
        'Minera El Colorado',
        'Minera Geometales SA',
        'Minera IRLAustralia',
        'Minera La Puna SA',
        'Minera Piuquenes SA',
        'Mirasol Resources Ltd',
        'New Dimension Resources Ltd',
        'Norsemont Mining Inc',
        'Orocobre Ltd',
        'Pachamama Resources Ltd',
        'Pacific Bay Minerals Ltd',
        'Pacific Rim Mining Corp',
        'Palladon Ventures Ltd',
        'Pan American Silver Corp',
        'Patagonia Gold PLC',
        'Peregrine Metals Ltd',
        'Petra Gold Servicios Mineros',
        'Plato Gold Corp',
        'Potash One Inc',
        'Quartz Minerals SA',
        'Rio Tinto plc',
        'Rodinia Minerals Inc',
        'Rome Resources Ltd',
        'Royal',
        'Silver Standard Resources Inc',
        'Silver Wheaton Corp',
        'Soltera Mining',
        'SOMICA DEM',
        'South American Salars Pty Ltd',
        'Sphere Resources Inc',
        'Stealth Minerals Ltd',
        'Strategic Resources Ltd',
        'Sumitomo Metal Mining C.O. Ltd',
        'Surminera SA',
        'Surnatron SA',
        'Teck Cominco Limited',
        'TNR Gold Corp',
        'Tolsa SA – Suc',
        'Trendix SA',
        'Troy Resources NL',
        'U308 Holdings Plc',
        'U3O8 Corporation',
        'Ulex SA',
        'Unimin Corp',
        'Uranco SA',
        'Uranio AG',
        'Vale',
        'Vega Gold Ltd',
        'Wealth Minerals',
        'Yamana Gold Inc',
        'Yamiri Gold and Energy Inc',
        'YMAD',
    ];
}