<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormAltaProductor extends Model
{
    use HasFactory;
    use SoftDeletes;
    
    protected $table = 'form_alta_productores';
    protected $date = ['created_at', 'deleted_at', 'updated_at'];
    protected $fillable = [
        'tipo_productor',
        'cuit',
        'cuit_correcto',
        'obs_cuit',
        'razonsocial',
        'razon_social_correcto',
        'obs_razon_social',
        'numeroproductor',
        'numeroproductor_correcto',
        'obs_numeroproductor',
        'email',
        'email_correcto',
        'obs_email',
        'tiposociedad',
        'tiposociedad_correcto',
        'obs_tiposociedad',
        'inscripciondgr',
        'inscripciondgr_correcto',
        'obs_inscripciondgr',
        'constaciasociedad',
        'constaciasociedad_correcto',
        'obs_constaciasociedad',
        'paso_1_progreso',
        'paso_1_aprobado',
        'paso_1_reprobado',
        'leal_calle',
        'leal_numero',
        'leal_telefono',
        'leal_pais',
        'leal_provincia',
        'leal_departamento',
        'leal_localidad',
        'leal_cp',
        'leal_otro',
        'administracion_calle',
        'administracion_numero',
        'administracion_telefono',
        'administracion_pais',
        'administracion_provincia',
        'administracion_departamento',
        'administracion_localidad',
        'administracion_cp',
        'administracion_otro',
        'numero_expdiente',
        'categoria',
        'nombre_mina',
        'descripcion_mina',
        'distrito_minero',
        'mina_cantera',
        'plano_inmueble',
        'minerales_variedad',
        'owner',
        'arrendatario',
        'concesionario',
        'otros',
        'titulo_contrato_posecion',
        'resolucion_concesion_minera',
        'constancia_pago_canon',
        'iia',
        'dia',
        'acciones_a_desarrollar',
        'actividad',
        'fecha_alta_dia',
        'fecha_vencimiento_dia',
        'localidad_mina_pais',
        'localidad_mina_provincia',
        'localidad_mina_departamento',
        'localidad_mina_localidad',
        'tipo_sistema',
        'longitud',
        'latitud',
        'created_by',
        'estado',
        'tipo_tramite',
        'updated_by',
        'tiposociedad_correcto',
        'created_by',
        'created_by',
        'updated_by',
        'updated_paso_uno',
        'updated_paso_dos',
        'leal_calle_correcto',
        'obs_leal_calle',
        'leal_numero_correcto',
        'obs_leal_numero',
        'leal_telefono_correcto',
        'obs_leal_telefono',
        'leal_provincia_correcto',
        'obs_leal_provincia',
        'leal_departamento_correcto',
        'obs_leal_departamento',
        'leal_localidad_correcto',
        'obs_leal_localidad',
        'leal_cp_correcto',
        'obs_leal_cp',
        'leal_otro_correcto',
        'obs_leal_otro',
        'paso_2_progreso',
        'paso_2_aprobado',
        'paso_2_reprobado',
        'administracion_calle_correcto',
        'obs_administracion_calle',
        'administracion_numero_correcto',
        'obs_administracion_numero',
        'administracion_telefono_correcto',
        'obs_administracion_telefono',
        'administracion_provincia_correcto',
        'obs_administracion_provincia',
        'administracion_departamento_correcto',
        'obs_administracion_departamento',
        'administracion_localidad_correcto',
        'obs_administracion_localidad',
        'administracion_cp_correcto',
        'obs_administracion_cp',
        'administracion_otro_correcto',
        'obs_administracion_otro',
        'paso_3_progreso',
        'paso_3_aprobado',
        'paso_3_reprobado',
        'numero_expdiente_correcto',
        'obs_numero_expdiente',
        'categoria_correcto',
        'obs_categoria',
        'nombre_mina_correcto',
        'obs_nombre_mina',
        'descripcion_mina_correcto',
        'obs_descripcion_mina',
        'obs_distrito_minero',
        'distrito_minero_correcto',
        'mina_cantera_correcto',
        'obs_mina_cantera',
        'plano_inmueble_correcto',
        'obs_plano_inmueble',
        'obs_resolucion_concesion_minera',
        'resolucion_concesion_minera_correcto',
        'titulo_contrato_posecion_correcto',
        'obs_titulo_contrato_posecion',
        'paso_4_progreso',
        'paso_4_aprobado',
        'paso_4_reprobado',
        'updated_paso_cuatro',
        'updated_paso_tres',
        'otro_caracter_acalaracion',
        'concesion_minera_acalracion',
        'sustancias_de_aprovechamiento_comun',
        'owner_correcto',
        'obs_owner',
        'arrendatario_correcto',
        'obs_arrendatario',
        'concesionario_correcto',
        'obs_concesionario',
        'otros_correcto',
        'obs_otros',
        'sustancias_de_aprovechamiento_comun_correcto',
        'obs_sustancias_de_aprovechamiento_comun_correcto',
        'constancia_pago_canon_correcto',
        'obs_constancia_pago_canon',
        'iia_correcto',
        'obs_iia',
        'dia_correcto',
        'obs_dia',
        'acciones_a_desarrollar_correcto',
        'obs_acciones_a_desarrollar',
        'actividad_correcto',
        'obs_actividad',
        'fecha_alta_dia_correcto',
        'obs_fecha_alta_dia',
        'paso_5_progreso',
        'paso_5_aprobado',
        'paso_5_reprobado',
        'fecha_vencimiento_dia_correcto',
        'obs_fecha_vencimiento_dia',
        'updated_paso_cinco',
        'localidad_mina_provincia_correcto',
		'obs_localidad_mina_provincia',
		'localidad_mina_departamento_correcto',
		'obs_localidad_mina_departamento',
		'localidad_mina_localidad_correcto',
		'obs_localidad_mina_localidad',
		'tipo_sistema_correcto',
		'obs_tipo_sistema',
		'longitud_correcto',
		'obs_longitud',
		'latitud_correcto',
		'obs_latitud',
		'paso_6_progreso',
		'paso_6_aprobado',
		'paso_6_reprobado',
		'updated_paso_seis',
        'sustancias_de_aprovechamiento_comun_aclaracion'

    ];
    
    
    
    /*id
    cuit
    razonsocial
    numeroproductor
    tiposociedad
    inscripciondgr
    constaciasociedad
    leal_calle
    leal_numero
    leal_telefono
    leal_pais
    leal_provincia
    leal_departamento
    leal_localidad
    leal_cp
    administracion_calle
    administracion_numero
    administracion_telefono
    administracion_pais
    administracion_provincia
    administracion_departamento
    administracion_localidad
    administracion_cp
    numero_expdiente
    categoria
    nombre_mina
    descripcion_mina
    distrito_minero
    mina_cantera
    plano_inmueble
    caracter_invoca
    titulo_contrato_posecion
    resolucion_concesion_minera
    constancia_pago_canon
    iia
    dia
    acciones_a_desarrollar
    actividad
    fecha_alta_dia
    fecha_vencimiento_dia
    localidad_mina_pais
    localidad_mina_provincia
    localidad_mina_departamento
    localidad_mina_localidad
    longitud
    latitud
    created_by
    estado
    created_at
    deleted_at
    updated_at
    */
}
